server:
  port: 10082
  servlet:
    context-path: dubbo-rpc
dubbo:
  application:
    name: dubbo-rpc
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
    contextpath: dubbo-rpc #配置rpc访问路径
  scan:
    base-packages: com.es.service
spring:
  application:
    name: dubbo-rpc
